# Generated by Django 3.2.18 on 2023-05-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreignkeyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_age',
            new_name='student_age',
        ),
    ]
